

        

const sections = [
    {
      sectionName: "Shirts",
      products: [
    { description: "Shirt - PT - PT - ", price: 69.00},
    { description: "Sides In (Flat Felled) - ", price: 43.00},
    { description: "Sleeves In (Flat Felled) -", price: 43.00},
    { description: "Sides and Sleeves In (Flat Felled) - ", price: 67.00},
    { description: "Gussets Add-on - ", price: 26.00},
    { description: "Add Darts -", price: 25.00},
    { description: "Remove Darts -", price: 25.00},
    { description: "Deepen Darts -", price: 30.00},
    { description: "Remove Back Pleats -", price: 67.00},
    { description: "Shorten Sleeve Cuff (per sleeve, customer must provide) -", price: 24.00},
    { description: "Shorten Sleeve Cuff and Placket (per sleeve, customer must provide) -", price: 40.00},
    { description: "Shorten Bottom -", price: 30.00},
    { description: "Attach Shirt Pocket -", price: 19.00},
      ],
    },

     {
      sectionName: "Pants",
      products: [
    { description: "Lower Back Waistband - ", price: 65.00},
    { description: "Lower Front Waistband -", price: 153.00},
    { description: "Lower Full Waistband -", price: 182.00},
    { description: "Attach Belt Loops Outside -", price: 40.00},
    { description: "Attach Belt Loops Inside -", price: 69.00},
    { description: "Make Belt Loops (6) -", price: 45.00},
    { description: "Waist -", price: 35.00},
    { description: "Seat -", price: 25.00},
    { description: "Waist/Seat -", price: 60.00},
    { description: "Waist/Seat recut through darts/sides -", price: 82.00},
    { description: "Split waistband add-on -", price: 13.00},
    { description: "Crotch -", price: 51.00},
    { description: "Waist/Seat/Crotch -", price: 77.00},
    { description: "Add Crotch Saddle -", price: 45.00},
    { description: "Taper -", price: 50.00},
    { description: "Taper (inside only and re-crease) -", price: 50.00},
    { description: "Taper w/ pickstitching -", price: 83.00},
    { description: "Taper through pockets -", price: 96.00},
    { description: "Taper through pockets w/ pickstitching - ", price: 138.00},
    { description: "Tux Pants Taper - both sides - re-attach stripe -", price: 182.00},
    { description: "Full recut/ remove pleats -", price: 226.00},
    { description: "Bottoms Plain -", price: 25.00},
    { description: "Bottoms Cuffs -", price: 30.00},
    { description: "Bottoms Plain (with heel guard) -", price: 30.00},
    { description: "Bottoms Cuffs (with heel guard) -", price: 35.00},
      ],
    },
    
    {
        sectionName: "Dresses & Gowns",
        products: [
    { description: "Reshape neckline:", price: 90.00},
    { description: "Reshape illusion neckline - no embellishment: ", price: 65.00},
    { description: "Reshape illusion neckline - w/ embelishment: ", price: 75.00},
    { description: "Straps - no lining:", price: 50.00},
    { description: "Straps - w/ lining:", price: 70.00},
    { description: "Straps - illusion top:", price: 60.00},
    { description: "Straps - illusion top - Bias tape:", price: 65.00},
    { description: "Straps - illusion top- w/ embelishment: ", price: 90.00},
    { description: "Shorten straps - spaghetti:", price: 45.00},
    { description: "Shoulders - w/ sleeve - no lining:", price: 85.00},
    { description: "Shoulders - w/ sleeve - no lining- bias tape cover:", price: 100.00},
    { description: "Shoulders - w/ sleeve - w/ lining:", price: 135.00},
    { description: "Shoulders - w/ sleeve - illusion top:", price: 105.00},
    { description: "Reset sleeves - no lining -:", price: 75.00},
    { description: "Reset sleeves - w/ lining-:", price: 105.00},
    { description: "Reshape armholes - no lining:", price: 60.00},
    { description: "Reshape armholes - w/ lining:", price: 85.00},
    { description: "Shorten sleeve - no lining - rolled hem (per sleeve):", price: 35.00},
    { description: "Shorten sleeve - w/lining - rolled hem (per sleeve):", price: 45.00},
    { description: "Shorten sleeve - Cut hem:", price: 40.00},
    { description: "Shorten sleeve - Cut hem w/ embellishment: ", price: 45.00},
    { description: "Shorten sleeve -no lining- w/ embellishment /remake Vent (per sleeve):", price: 75.00},
    { description: "Shorten sleeve - w/ lining - w/ embellishment/ remake vent (per sleeve):", price: 105.00},
    { description: "Shorten sleeve from shoulder - no lining (per sleeve):", price: 80.00},
    { description: "Shorten sleeve from shoulder - w/ lining (per sleeve):", price: 100.00},
    { description: "Sides top - no lining - Zero @ waist seam: ", price: 40.00},
    { description: "Sides top - no lining - Blend past waist seam: ", price: 60.00},
    { description: "Sides top - no lining w/ embellishment - Zero @ waist seam: ", price: 65.00},
    { description: "Sides top - no lining w/ embelishment - Blend past waist seam: ", price: 85.00},
    { description: "Sides top - w/ lining- Zero @ waist seam: ", price: 75.00},
    { description: "Sides top - w/ lining - Blend past waist seam: ", price: 85.00},
    { description: "Sides top - w/ lining - w/ embelishment -Zero @ waist seam: ", price: 120.00},
    { description: "Sides top - w/ lining - w/ embelishment - Blend past waist seam:", price: 120.00},
    { description: "Sides top - w/ lining - w/ embelishment 3rd layer:", price: 135.00},
    { description: "Sides top from zipper - no lining:", price: 60.00},
    { description: "Sides top from zipper - w/ lining:", price: 90.00},
    { description: "Sides top from zipper w/ lining - w/ embelishment / Buttons: ", price: 105.00},
    { description: "Princess seams top - no lining:", price: 60.00},
    { description: "Princess seams top - w/ lining:", price: 75.00},
    { description: "Princess seams top - w/ lining w/ embelishment:", price: 100.00},
    { description: "Corset back conversion (white/ivory only) - Including making laces:", price: 190.00},
    { description: "Corset back conversion (white/ivory only) - No laces:", price: 150.00},
    { description: "Adding gussets - no sleeves:", price: 125.00},
    { description: "Adding gussets - w/ sleeve:", price: 150.00},
    { description: "Taper sleeve - straight seam:", price: 65.00},
    { description: "Taper sleeve - straight seam - remake vent: ", price: 130.00},
    { description: "Taper sleeve - french seam:", price: 85.00},
    { description: "Taper sleeve - french seam - remake vent: ", price: 130.00},
    { description: "Add waist darts - no lining:", price: 40.00},
    { description: "Add waist darts - w/ lining:", price: 55.00},
    { description: "Add waist darts - w/ lining embellishment: ", price: 65.00},
    { description: "Add bust darts - no lining:", price: 45.00},
    { description: "Add bust darts - w/ lining:", price: 60.00},
    { description: "Add bust darts - w/ lining embellishment: ", price: 70.00},
    { description: "Shorten hem from waist & taper:", price: 240.00},
    { description: "Shorten hem from waist & taper - w/ embellishment:", price: 250.00},
    { description: "Sides bottom - no lining -Zero @ waist seam: ", price: 55.00},
    { description: "Sides bottom - no lining - Blend past waist seam:", price: 60.00},
    { description: "Sides bottom - w/ lining- Zero @ waist seam: ", price: 70.00},
    { description: "Sides bottom - w/ lining - Blend past waist seam:", price: 75.00},
    { description: "Sides bottom - w/ lining w/ embelishment - Zero @ waist seam: ", price: 90.00},
    { description: "Sides bottom - w/ lining w/ embelishment - Blend past waist seam:", price: 95.00},
    { description: "Princess seams bottom - no lining:", price: 55.00},
    { description: "Princess seams bottom - w/ lining:", price: 70.00},
    { description: "Princess seams bottom - w/ lining & 3rd layer / embelishment:", price: 110.00},
    { description: "0-60 - serged / cut:", price: 50.00},
    { description: "61-120 - serged / cut:", price: 60.00},
    { description: "121- 180- serged / cut:", price: 70.00},
    { description: "181-240- serged / cut:", price: 80.00},
    { description: "0-60 - Machine rolled hem:", price: 65.00},
    { description: "61-120- Machine rolled hem:", price: 90.00},
    { description: "121- 180- Machine rolled hem:", price: 120.00},
    { description: "181-240- Machine rolled hem:", price: 145.00},
    { description: "0-60- Horse hair hem:", price: 80.00},
    { description: "61-120 -Horse hair hem:", price: 105.00},
    { description: "121- 180 -Horse hair hem:", price: 130.00},
    { description: "181-240 - Horse hair hem:", price: 155.00},
    { description: "0-60 - Lace Hem:", price: 65.00},
    { description: "61-120- Lace Hem:", price: 130.00},
    { description: "121- 180- Lace Hem:", price: 190.00},
    { description: "181-240- Lace Hem:", price: 240.00},
    { description: "0-60 - Blind hem:", price: 90.00},
    { description: "61-120- Blind Hem:", price: 105.00},
    { description: "121- 180- Blind Hem:", price: 120.00},
    { description: "181-240- Blind Hem:", price: 130.00},
    { description: "Hem w/ mitered & corner hem- no lining: ", price: 80.00},
    { description: "Hem w/ mitered & corner hem- lining:", price: 105.00},
    { description: "Bustle (first 3 point):", price: 40.00},
    { description: "Bustle (additional point):", price: 15.00},
    { description: "Add hook/snap/tack:", price: 20.00},
    { description: "Add bra cups:", price: 40.00},
    { description: "Add bra loops:", price: 25.00},
    { description: "Sew in belt/sash to zipper & tacks at front: ", price: 55.00},
    { description: "Sew in beaded belt to zipper:", price: 65.00},
    { description: "Sew on premade embelishment - 6 Inches: ", price: 30.00},
    { description: "Add boning - per seam - no topstitching: ", price: 30.00},
    { description: "Remove boning - per seam:", price: 20.00},
    { description: "Modesty piece:", price: 85.00},
    { description: "Replace bridal loops:", price: 60.00},
    { description: "button replacement:", price: 15.00},
    { description: "Steam dress:", price: 30.00},
    { description: "Steam gown:", price: 40.00},

        ],
      },



      {
        sectionName: "Skirts",
        products: [
    { description: "Waist - w/ zipper - no lining:", price: 60.00},
    { description: "Waist - w/ zipper - lining:", price: 80.00},
    { description: "Sides - no lining:", price: 40.00},
    { description: "Sides - no lining & waistband:", price: 55.00},
    { description: "Sides - w/ lining:", price: 55.00},
    { description: "Sides - w/ lining & waistband:", price: 70.00},
    { description: "Princess seams - no lining:", price: 40.00},
    { description: "Princess seams - w/ lining:", price: 55.00},
    { description: "Add darts - no lining:", price: 35.00},
    { description: "Add darts - w/ lining:", price: 50.00},

  
        ],
      },

      {
        sectionName: "Jackets & Blazers",
        products: [
    { description: "Lower Collar -", price: 45.00},
    { description: "Shorten Back -", price: 72.00},
    { description: "Pt. to Pt. -", price: 149.00},
    { description: "Pt. to Pt. w/ pickstitching -", price: 174.00},
    { description: "Shorten Collar - under 3/4 -", price: 100.00},
    { description: "Shorten Collar - over 3/4 and take in center -", price: 149.00},
    { description: "Shorten Collar - over 3/4 and rebalance shoulders -", price: 264.00},
    { description: "Shorten Lapels from front panels -", price: 264.00},
    { description: "Rebalance/reslope Shoulders -", price: 162.00},
    { description: "Add/Replace Shoulder Pads -", price: 64.00},
    { description: "Rotate Sleeve (per sleeve) -", price: 64.00},
    { description: "Replace Coat Sleeve (per sleeve) -", price: 64.00},
    { description: "Ease Armholes -", price: 37.00},
    { description: "Deepen Armholes -", price: 83.00},
    { description: "Taper Sleeve at inseam (PER SLEEVE) -", price: 35.00},
    { description: "Taper Sleeve at outseam (per sleeve) -", price: 87.00},
    { description: "Taper Sleeve at outseam w/ pickstitch (per sleeve) -", price: 103.00},
    { description: "Taper Sleeve outseam and inseam (per sleeve) - ", price: 112.00},
    { description: "Taper Sleeve outseam and inseam w/ pickstitch (per sleeve) - ", price: 128.00},
    { description: "Shorten/Lengthen Sleeve (per sleeve) -", price: 36.00},
    { description: "Shorten/Lengthen Sleeve w/ pic stitch (per sleeve) -", price: 50.00},
    { description: "Shorten Sleeve From Shoulder (per sleeve) - ", price: 103.00},
    { description: "Shorten Sleeve From Shoulder w/ pickstitch (per sleeve) - ", price: 117.00},
    { description: "Shorten/Lengthen Sleeve w/ New Vent Construction (2+) (per sleeve) -", price: 62.00},
    { description: "Close/finish Sleeve (per sleeve) -", price: 20.00},
    { description: "Remove Faux Buttonholes (easy) -", price: 20.00},
    { description: "Remove Faux Buttonholes (hard) -", price: 47.00},
    { description: "Machine Functional Button Holes (both sleeves, 4 per, same color) -", price: 65.00},
    { description: "Machine NON-Functional Button Holes (both sleeves, 4 per, same color) - ", price: 65.00},
    { description: "Attach Coat Sleeves Buttons (set) (Per Button)-", price: 9.00},
    { description: "Purchase and Attach Coat Buttons (full set, sleeves and body) -", price: 25.00},
    { description: "Add Elbow Patches -", price: 64.00},
    { description: "Sides  ", price: 45.00},
    { description: "Sides Through Vents -", price: 71.00},
    { description: "Sides Through Blades -", price: 79.00},
    { description: "Sides Through Blades and Vents -", price: 108.00},
    { description: "Sides through front -", price: 80.00},
    { description: "Center -", price: 38.00},
    { description: "Center through Vent -", price: 57.00},
    { description: "Center and Sides -", price: 75.00},
    { description: "Center and Sides Through Blades -", price: 108.00},
    { description: "Center and Sides Through Vents -", price: 96.00},
    { description: "Center and Sides Through Blades & Vents - ", price: 137.00},
    { description: "Add Jacket Vent (per) -", price: 72.00},
    { description: "Close Jacket Vent (per) -", price: 38.00},
    { description: "Reduce Chest -", price: 133.00},
    { description: "Shorten Coat -", price: 116.00},
    { description: "Lengthen Coat (Back Only) -", price: 116.00},


    ],
    },

    {
    sectionName: "Unlined Jackets",
    products: [
    { description: "Sides", price: 58.00},
    { description: "Sides Through Vents -", price: 83.00},
    { description: "Sides Through Blades -", price: 93.00},
    { description: "Sides Through Blades and Vents -", price: 123.00},
    { description: "Sides through front -", price: 103.00},
    { description: "Center -", price: 51.00},
    { description: "Center Through Vent -", price: 64.00},
    { description: "Center and Sides -", price: 85.00},
    { description: "Center and Sides Through Vents -", price: 115.00},
    { description: "Center and Sides Through Blades -", price: 123.00},
    { description: "Center and Sides Through Blades and Vents -", price: 152.00},
    { description: "Shorten Coat -", price: 131.00},

    ],
    },

    {
    sectionName: "Pick-Stitched Jackets",
    products: [
    { description: "Sides -", price: 58.00},
    { description: "Sides Through Vents -", price: 83.00},
    { description: "Sides Through Blades -", price: 93.00},
    { description: "Sides Through Blades and Vents -", price: 123.00},
    { description: "Sides through front -", price: 103.00},
    { description: "Center -", price: 51.00},
    { description: "Center Through Vent -", price: 64.00},
    { description: "Center and Sides -", price: 85.00},
    { description: "Center and Sides Through Vents -", price: 115.00},
    { description: "Center and Sides Through Blades -", price: 123.00},
    { description: "Center and Sides Through Blades and Vents - ", price: 152.00},
    { description: "Shorten Coat -", price: 125.00},
  
        ],
      },

      {
        sectionName: "Unlined & Pick-Stitched Jackets",
        products: [
    { description: "Sides -", price: 71.00},
    { description: "Sides Through Vents -", price: 96.00},
    { description: "Sides Through Blades -", price: 108.00},
    { description: "Sides Through Blades and Vents -", price: 137.00},
    { description: "Sides through front -", price: 120.00},
    { description: "Center -", price: 58.00},
    { description: "Center Through Vent -", price: 71.00},
    { description: "Center and Sides -", price: 103.00},
    { description: "Center and Sides Through Vents -", price: 128.00},
    { description: "Center and Sides Through Blades -", price: 145.00},
    { description: "Center and Sides Through Blades and Vents -", price: 174.00},
    { description: "Shorten Coat -", price: 145.00},
  
        ],
      },


      {
        sectionName: "Outerwear",
        products: [
    { description: "Sides -", price: 60.00},
    { description: "Sides through vents -", price: 80.00},
    { description: "Sides through blades -", price: 86.00},
    { description: "Sides through blades and vents -", price: 101.00},
    { description: "Center -", price: 58.00},
    { description: "Center through vent -", price: 93.00},
    { description: "Center and Sides -", price: 100.00},
    { description: "Center and sides through vents -", price: 103.00},
    { description: "Center and sides through blades -", price: 115.00},
    { description: "Center and sides through blades and vents - ", price: 130.00},
    { description: "Sleeve w/ cuff/belt/detail (per sleeve) - ", price: 50.00},
    { description: "Shorten Coat -", price: 116.00},
  
        ],
      },


      {
        sectionName: "Blouses",
        products: [
    { description: "Reshape neckline:", price: 90.00},
    { description: "Shoulders - no sleeve - no lining:", price: 50.00},
    { description: "Shoulders - no sleeve - w/ lining:", price: 75.00},
    { description: "Shoulders - w/ sleeve - no lining:", price: 90.00},
    { description: "Shoulders - w/ sleeve - w/ lining:", price: 125.00},
    { description: "Shoulders - no sleeve - illusion top:", price: 45.00},
    { description: "Shoulders - w/ sleeve - illusion top:", price: 105.00},
    { description: "Reset sleeves - no lining:", price: 90.00},
    { description: "Reset sleeves - w/ lining:", price: 105.00},
    { description: "Reshape armholes - no lining:", price: 60.00},
    { description: "Reshape armholes - w/ lining:", price: 75.00},
    { description: "Shorten sleeve - no lining - rolled hem (per sleeve):", price: 30.00},
    { description: "Shorten sleeve - w/lining - rolled hem (per sleeve):", price: 45.00},
    { description: "Shorten sleeve - no lining - w/ embelishment (per sleeve):", price: 50.00},
    { description: "Shorten sleeve - w/ lining - w/ embelishment (per sleeve): ", price: 60.00},
    { description: "Shorten sleeve from shoulder - no lining (per sleeve):", price: 80.00},
    { description: "Shorten sleeve from shoulder - w/ lining (per sleeve):", price: 95.00},
    { description: "Sides top - no lining - French seam:", price: 60.00},
    { description: "Sides top - w/ lining - French Seam:", price: 85.00},
    { description: "Sides top - no lining:", price: 45.00},
    { description: "Sides top - w/ lining:", price: 60.00},
    { description: "Princess seams top - no lining:", price: 45.00},
    { description: "Princess seams top - w/ lining:", price: 60.00},
        
  
        ],
      },


      {
        sectionName: "Jeans",
        products: [
    { description: "Jeans Waist -", price: 58.00},
    { description: "Jeans Waist/Seat -", price: 70.00},
    { description: "Jeans Original Hem -", price: 30.00},
    { description: "Finished Hem -", price: 25.00},
  
        ],
      },

      {
        sectionName: "Vest",
        products: [
    { description: "Raise/Shorten Back -", price: 83.00},
    { description: "Raise/Shorten Back over 1 -", price: 138.00},
    { description: "Sides -", price: 45.00},
    { description: "Center -", price: 35.00},
    { description: "Sides and Center -", price: 65.00},
    { description: "Reshape Armholes -", price: 58.00},
    { description: "Shorten from Shoulders -", price: 58.00},
    { description: "Shorten from Shoulders Over 1 -", price: 138.00},
    { description: "Shorten from Bottom -", price: 64.00},
    { description: "Lengthen from Bottom (Back Only) -", price: 64.00},
        
  
        ],
      },

      {
        sectionName: "Small Repairs",
        products: [
    { description: "Button (per button) -", price: 9.00},
    { description: "Replace jean button -", price: 18.00},
    { description: "Fabric Button -", price: 17.00},
    { description: "Add Suspender Buttons -", price: 27.00}
        
  
        ],
      },

    ];


// export { products };
export { sections };